name: 'Git Status Check'
description: 'Checks the git status for unexpected changes'
inputs:
  allowed-changes:
    required: false
    description: Globs for files we expect might have valid changes, separated with newlines.
  continue-with-unexpected-changes:
    required: false
    default: "false"
    description: Report changes as warnings rather than errors and continue.
  dir:
    description: Directory within which to check git status. This path is relative to $GITHUB_WORKSPACE
    required: false
    default: "."
  ignore-new-files:
    required: false
    description: Only check for updated or deleted files.
outputs:
  unexpected-changes-count:
    description: 'The number of unexpected changes.'
runs:
  using: 'node20'
  main: 'dist/index.js'
